# yaml-language-server: $schema=./.vscode/coderabbit-schema.json
language: "ko-KR"

tone_instructions: |
  보안, 버그, 성능 이슈에만 집중하세요.
  사소한 스타일 제안은 하지 마세요.
  프로젝트 컨벤션 위반 시 명확하게 지적하세요.

reviews:
  profile: "chill"
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  collapse_walkthrough: true
  poem: false
  review_status: false
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "wip"
      - "DO NOT MERGE"
  auto_incremental_review: true
  tools:
    markdownlint:
      enabled: false
  path_filters:
    - "app/src/**"
    - "app/supabase/migrations/**"
    - "!app/src/lib/database.types.ts"
    - "!**/node_modules/**"
    - "!**/.next/**"
    - "!**/*.lock"
    - "!**/*.log"
  path_instructions:
    - path: "app/src/app/(page)/**"
      instructions: |
        프론트엔드 컴포넌트 리뷰 시 다음을 확인:
        1. Supabase(DB) 직접 호출 금지 (예외: supabase.auth.*, Storage signed URL)
        2. Server Action 사용 금지
        3. React Query는 커스텀 훅으로 래핑하지 말고 컴포넌트에서 직접 사용
        4. onError 콜백 금지 - 중앙 에러 핸들러 사용
        5. 데이터 통신은 /api/** BFF 경유 필수

    - path: "app/src/app/api/**"
      instructions: |
        API Route(BFF) 리뷰 시 다음을 확인:
        1. withApi 미들웨어로 감싸져 있는지
        2. 입력값은 Zod 스키마로 파싱하는지
        3. 에러는 ApiError(badRequest, notFound 등)로 던지는지
        4. 응답은 ok/created/fail 표준 포맷 사용하는지
        5. 권한 체크는 withAuth/withRole 가드 사용하는지

    - path: "app/src/lib/schema/**"
      instructions: |
        Zod 스키마 리뷰 시 다음을 확인:
        1. 도메인별 단일 파일 패턴 유지
        2. 과도한 파일 분할 금지

    - path: "app/src/server/**"
      instructions: |
        서버 모듈 리뷰 시 다음을 확인:
        1. repository.ts: DB 쿼리 모음
        2. mapper.ts: Row → DTO 변환 (snake_case → camelCase)
        3. Supabase 에러는 ApiError로 변환

    - path: "app/supabase/migrations/**"
      instructions: |
        마이그레이션 SQL 리뷰 시 다음을 확인:
        1. 이미 적용된 마이그레이션 파일은 수정 금지
        2. RLS 정책 정의 여부
        3. enable row level security 적용 여부
