/* eslint-disable */
/* This file is auto-generated by `pnpm db:gen`. Do not edit manually. */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ad_campaigns: {
        Row: {
          ad_slot_id: string
          advertiser_name: string
          created_at: string
          created_by: string
          ends_at: string
          id: string
          monthly_price: number
          starts_at: string
          status: Database["public"]["Enums"]["ad_campaign_status"]
          total_clicks: number
          total_impressions: number
          updated_at: string
          vendor_id: string | null
        }
        Insert: {
          ad_slot_id: string
          advertiser_name: string
          created_at?: string
          created_by: string
          ends_at: string
          id?: string
          monthly_price?: number
          starts_at: string
          status?: Database["public"]["Enums"]["ad_campaign_status"]
          total_clicks?: number
          total_impressions?: number
          updated_at?: string
          vendor_id?: string | null
        }
        Update: {
          ad_slot_id?: string
          advertiser_name?: string
          created_at?: string
          created_by?: string
          ends_at?: string
          id?: string
          monthly_price?: number
          starts_at?: string
          status?: Database["public"]["Enums"]["ad_campaign_status"]
          total_clicks?: number
          total_impressions?: number
          updated_at?: string
          vendor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ad_campaigns_ad_slot_id_fkey"
            columns: ["ad_slot_id"]
            isOneToOne: false
            referencedRelation: "ad_slots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_campaigns_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_campaigns_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_click_logs: {
        Row: {
          campaign_id: string
          clicked_at: string
          creative_id: string
          id: string
          ip_address: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          campaign_id: string
          clicked_at?: string
          creative_id: string
          id?: string
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          campaign_id?: string
          clicked_at?: string
          creative_id?: string
          id?: string
          ip_address?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ad_click_logs_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_click_logs_creative_id_fkey"
            columns: ["creative_id"]
            isOneToOne: false
            referencedRelation: "ad_creatives"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_creatives: {
        Row: {
          campaign_id: string
          click_url: string
          created_at: string
          html_content: string | null
          id: string
          image_url: string | null
          is_active: boolean
          sort_order: number
          title: string
          type: Database["public"]["Enums"]["ad_creative_type"]
          updated_at: string
        }
        Insert: {
          campaign_id: string
          click_url: string
          created_at?: string
          html_content?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          sort_order?: number
          title: string
          type?: Database["public"]["Enums"]["ad_creative_type"]
          updated_at?: string
        }
        Update: {
          campaign_id?: string
          click_url?: string
          created_at?: string
          html_content?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          sort_order?: number
          title?: string
          type?: Database["public"]["Enums"]["ad_creative_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_creatives_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_impressions: {
        Row: {
          campaign_id: string
          clicks: number
          created_at: string
          date: string
          id: string
          impressions: number
          updated_at: string
        }
        Insert: {
          campaign_id: string
          clicks?: number
          created_at?: string
          date: string
          id?: string
          impressions?: number
          updated_at?: string
        }
        Update: {
          campaign_id?: string
          clicks?: number
          created_at?: string
          date?: string
          id?: string
          impressions?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_impressions_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_priority_jumpups: {
        Row: {
          activated_at: string
          created_at: string
          expires_at: string
          id: string
          purchase_id: string
        }
        Insert: {
          activated_at?: string
          created_at?: string
          expires_at: string
          id?: string
          purchase_id: string
        }
        Update: {
          activated_at?: string
          created_at?: string
          expires_at?: string
          id?: string
          purchase_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_priority_jumpups_purchase_id_fkey"
            columns: ["purchase_id"]
            isOneToOne: false
            referencedRelation: "ad_priority_purchases"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_priority_purchases: {
        Row: {
          category_id: string
          created_at: string
          credit_transaction_id: string | null
          ends_at: string
          id: string
          jumpup_last_used_at: string | null
          jumpup_remaining: number
          price_paid: number
          priority_slot_id: string
          starts_at: string
          status: Database["public"]["Enums"]["ad_priority_purchase_status"]
          tier: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at: string
          vendor_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          credit_transaction_id?: string | null
          ends_at: string
          id?: string
          jumpup_last_used_at?: string | null
          jumpup_remaining?: number
          price_paid?: number
          priority_slot_id: string
          starts_at: string
          status?: Database["public"]["Enums"]["ad_priority_purchase_status"]
          tier: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at?: string
          vendor_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          credit_transaction_id?: string | null
          ends_at?: string
          id?: string
          jumpup_last_used_at?: string | null
          jumpup_remaining?: number
          price_paid?: number
          priority_slot_id?: string
          starts_at?: string
          status?: Database["public"]["Enums"]["ad_priority_purchase_status"]
          tier?: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_priority_purchases_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_priority_purchases_priority_slot_id_fkey"
            columns: ["priority_slot_id"]
            isOneToOne: false
            referencedRelation: "ad_priority_slots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_priority_purchases_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_priority_slots: {
        Row: {
          category_id: string
          created_at: string
          id: string
          is_active: boolean
          max_slots: number
          price_weekly: number
          sort_order: number
          tier: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at: string
        }
        Insert: {
          category_id: string
          created_at?: string
          id?: string
          is_active?: boolean
          max_slots?: number
          price_weekly?: number
          sort_order?: number
          tier: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at?: string
        }
        Update: {
          category_id?: string
          created_at?: string
          id?: string
          is_active?: boolean
          max_slots?: number
          price_weekly?: number
          sort_order?: number
          tier?: Database["public"]["Enums"]["ad_priority_tier"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_priority_slots_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_slots: {
        Row: {
          created_at: string
          display_count: number
          id: string
          is_active: boolean
          max_campaigns: number
          name: string
          position: Database["public"]["Enums"]["ad_slot_position"]
          price_monthly: number
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_count?: number
          id?: string
          is_active?: boolean
          max_campaigns?: number
          name: string
          position: Database["public"]["Enums"]["ad_slot_position"]
          price_monthly?: number
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_count?: number
          id?: string
          is_active?: boolean
          max_campaigns?: number
          name?: string
          position?: Database["public"]["Enums"]["ad_slot_position"]
          price_monthly?: number
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string
          actor_user_id: string
          created_at: string
          id: string
          metadata: Json
          target_id: string | null
          target_type: string
        }
        Insert: {
          action: string
          actor_user_id: string
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type: string
        }
        Update: {
          action?: string
          actor_user_id?: string
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey"
            columns: ["actor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      bid_contracts: {
        Row: {
          commission_amount: number
          commission_status: Database["public"]["Enums"]["bid_commission_status"]
          commission_transaction_id: string | null
          contract_amount: number
          created_at: string
          id: string
          project_id: string
          response_id: string
          updated_at: string
          vendor_id: string
        }
        Insert: {
          commission_amount?: number
          commission_status?: Database["public"]["Enums"]["bid_commission_status"]
          commission_transaction_id?: string | null
          contract_amount: number
          created_at?: string
          id?: string
          project_id: string
          response_id: string
          updated_at?: string
          vendor_id: string
        }
        Update: {
          commission_amount?: number
          commission_status?: Database["public"]["Enums"]["bid_commission_status"]
          commission_transaction_id?: string | null
          contract_amount?: number
          created_at?: string
          id?: string
          project_id?: string
          response_id?: string
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bid_contracts_commission_transaction_id_fkey"
            columns: ["commission_transaction_id"]
            isOneToOne: false
            referencedRelation: "credit_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bid_contracts_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: true
            referencedRelation: "bid_projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bid_contracts_response_id_fkey"
            columns: ["response_id"]
            isOneToOne: false
            referencedRelation: "bid_responses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bid_contracts_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      bid_project_scores: {
        Row: {
          created_at: string
          id: string
          is_recommended: boolean
          portfolio_score: number
          price_score: number
          project_id: string
          rating_score: number
          region_score: number
          response_score: number
          total_score: number
          vendor_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_recommended?: boolean
          portfolio_score?: number
          price_score?: number
          project_id: string
          rating_score?: number
          region_score?: number
          response_score?: number
          total_score?: number
          vendor_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_recommended?: boolean
          portfolio_score?: number
          price_score?: number
          project_id?: string
          rating_score?: number
          region_score?: number
          response_score?: number
          total_score?: number
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bid_project_scores_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "bid_projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bid_project_scores_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      bid_project_status_history: {
        Row: {
          changed_by: string | null
          created_at: string
          from_status: Database["public"]["Enums"]["bid_project_status"] | null
          id: string
          project_id: string
          to_status: Database["public"]["Enums"]["bid_project_status"]
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["bid_project_status"] | null
          id?: string
          project_id: string
          to_status: Database["public"]["Enums"]["bid_project_status"]
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["bid_project_status"] | null
          id?: string
          project_id?: string
          to_status?: Database["public"]["Enums"]["bid_project_status"]
        }
        Relationships: [
          {
            foreignKeyName: "bid_project_status_history_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "bid_projects"
            referencedColumns: ["id"]
          },
        ]
      }
      bid_projects: {
        Row: {
          attachments: Json
          bid_deadline: string | null
          budget_max: number
          budget_min: number
          created_at: string
          doctor_user_id: string
          id: string
          location: string
          requirements: string | null
          schedule: string | null
          space_size: string | null
          status: Database["public"]["Enums"]["bid_project_status"]
          title: string
          updated_at: string
        }
        Insert: {
          attachments?: Json
          bid_deadline?: string | null
          budget_max?: number
          budget_min?: number
          created_at?: string
          doctor_user_id: string
          id?: string
          location: string
          requirements?: string | null
          schedule?: string | null
          space_size?: string | null
          status?: Database["public"]["Enums"]["bid_project_status"]
          title: string
          updated_at?: string
        }
        Update: {
          attachments?: Json
          bid_deadline?: string | null
          budget_max?: number
          budget_min?: number
          created_at?: string
          doctor_user_id?: string
          id?: string
          location?: string
          requirements?: string | null
          schedule?: string | null
          space_size?: string | null
          status?: Database["public"]["Enums"]["bid_project_status"]
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      bid_responses: {
        Row: {
          attachments: Json
          created_at: string
          estimated_days: number | null
          id: string
          price: number | null
          project_id: string
          proposal: string | null
          status: Database["public"]["Enums"]["bid_response_status"]
          submitted_at: string | null
          updated_at: string
          vendor_id: string
        }
        Insert: {
          attachments?: Json
          created_at?: string
          estimated_days?: number | null
          id?: string
          price?: number | null
          project_id: string
          proposal?: string | null
          status?: Database["public"]["Enums"]["bid_response_status"]
          submitted_at?: string | null
          updated_at?: string
          vendor_id: string
        }
        Update: {
          attachments?: Json
          created_at?: string
          estimated_days?: number | null
          id?: string
          price?: number | null
          project_id?: string
          proposal?: string | null
          status?: Database["public"]["Enums"]["bid_response_status"]
          submitted_at?: string | null
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "bid_responses_project_id_fkey"
            columns: ["project_id"]
            isOneToOne: false
            referencedRelation: "bid_projects"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bid_responses_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          created_at: string
          depth: number
          id: string
          is_active: boolean
          name: string
          parent_id: string | null
          slug: string
          sort_order: number
          tier: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          depth?: number
          id?: string
          is_active?: boolean
          name: string
          parent_id?: string | null
          slug: string
          sort_order?: number
          tier?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          depth?: number
          id?: string
          is_active?: boolean
          name?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number
          tier?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      credit_accounts: {
        Row: {
          auto_charge_amount: number | null
          auto_charge_enabled: boolean
          auto_charge_threshold: number
          balance: number
          created_at: string
          id: string
          updated_at: string
          vendor_id: string
        }
        Insert: {
          auto_charge_amount?: number | null
          auto_charge_enabled?: boolean
          auto_charge_threshold?: number
          balance?: number
          created_at?: string
          id?: string
          updated_at?: string
          vendor_id: string
        }
        Update: {
          auto_charge_amount?: number | null
          auto_charge_enabled?: boolean
          auto_charge_threshold?: number
          balance?: number
          created_at?: string
          id?: string
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "credit_accounts_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: true
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      credit_packages: {
        Row: {
          amount: number
          bonus_rate: number
          created_at: string
          id: string
          is_active: boolean
          name: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          amount: number
          bonus_rate?: number
          created_at?: string
          id?: string
          is_active?: boolean
          name: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          amount?: number
          bonus_rate?: number
          created_at?: string
          id?: string
          is_active?: boolean
          name?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      credit_transactions: {
        Row: {
          amount: number
          balance_after: number
          created_at: string
          credit_account_id: string
          description: string | null
          expires_at: string | null
          id: string
          metadata: Json | null
          payment_id: string | null
          status: Database["public"]["Enums"]["credit_transaction_status"]
          type: Database["public"]["Enums"]["credit_transaction_type"]
          updated_at: string
        }
        Insert: {
          amount: number
          balance_after?: number
          created_at?: string
          credit_account_id: string
          description?: string | null
          expires_at?: string | null
          id?: string
          metadata?: Json | null
          payment_id?: string | null
          status?: Database["public"]["Enums"]["credit_transaction_status"]
          type: Database["public"]["Enums"]["credit_transaction_type"]
          updated_at?: string
        }
        Update: {
          amount?: number
          balance_after?: number
          created_at?: string
          credit_account_id?: string
          description?: string | null
          expires_at?: string | null
          id?: string
          metadata?: Json | null
          payment_id?: string | null
          status?: Database["public"]["Enums"]["credit_transaction_status"]
          type?: Database["public"]["Enums"]["credit_transaction_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "credit_transactions_credit_account_id_fkey"
            columns: ["credit_account_id"]
            isOneToOne: false
            referencedRelation: "credit_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fk_credit_transactions_payment"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
        ]
      }
      doctor_verifications: {
        Row: {
          birth_date: string | null
          clinic_name: string | null
          created_at: string
          full_name: string
          id: string
          license_file_id: string | null
          license_no: string
          reject_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["verification_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          birth_date?: string | null
          clinic_name?: string | null
          created_at?: string
          full_name: string
          id?: string
          license_file_id?: string | null
          license_no: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          birth_date?: string | null
          clinic_name?: string | null
          created_at?: string
          full_name?: string
          id?: string
          license_file_id?: string | null
          license_no?: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "doctor_verifications_license_file_id_fkey"
            columns: ["license_file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctor_verifications_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctor_verifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      favorites: {
        Row: {
          created_at: string
          user_id: string
          vendor_id: string
        }
        Insert: {
          created_at?: string
          user_id: string
          vendor_id: string
        }
        Update: {
          created_at?: string
          user_id?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      files: {
        Row: {
          bucket: string
          created_at: string
          id: string
          mime_type: string | null
          owner_user_id: string
          path: string
          purpose: Database["public"]["Enums"]["file_purpose"]
          size_bytes: number | null
        }
        Insert: {
          bucket: string
          created_at?: string
          id?: string
          mime_type?: string | null
          owner_user_id: string
          path: string
          purpose: Database["public"]["Enums"]["file_purpose"]
          size_bytes?: number | null
        }
        Update: {
          bucket?: string
          created_at?: string
          id?: string
          mime_type?: string | null
          owner_user_id?: string
          path?: string
          purpose?: Database["public"]["Enums"]["file_purpose"]
          size_bytes?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "files_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      help_articles: {
        Row: {
          category_id: string | null
          content: string
          created_at: string
          created_by: string
          display_order: number
          id: string
          is_pinned: boolean
          is_published: boolean
          title: string
          type: Database["public"]["Enums"]["help_article_type"]
          updated_at: string
        }
        Insert: {
          category_id?: string | null
          content: string
          created_at?: string
          created_by: string
          display_order?: number
          id?: string
          is_pinned?: boolean
          is_published?: boolean
          title: string
          type: Database["public"]["Enums"]["help_article_type"]
          updated_at?: string
        }
        Update: {
          category_id?: string | null
          content?: string
          created_at?: string
          created_by?: string
          display_order?: number
          id?: string
          is_pinned?: boolean
          is_published?: boolean
          title?: string
          type?: Database["public"]["Enums"]["help_article_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "help_articles_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "help_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "help_articles_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      help_categories: {
        Row: {
          created_at: string
          display_order: number
          id: string
          is_active: boolean
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      lead_attachments: {
        Row: {
          created_at: string
          created_by: string | null
          file_id: string
          id: string
          lead_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          file_id: string
          id?: string
          lead_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          file_id?: string
          id?: string
          lead_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_attachments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_attachments_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_attachments_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_charges: {
        Row: {
          charge_transaction_id: string | null
          created_at: string
          credit_account_id: string
          duplicate_of_lead_id: string | null
          id: string
          is_duplicate: boolean
          lead_id: string
          no_response_warned_at: string | null
          price_breakdown: Json
          refund_amount: number | null
          refund_reason:
            | Database["public"]["Enums"]["lead_charge_refund_reason"]
            | null
          refund_transaction_id: string | null
          refunded_at: string | null
          status: Database["public"]["Enums"]["lead_charge_status"]
          total_amount: number
          updated_at: string
          vendor_id: string
        }
        Insert: {
          charge_transaction_id?: string | null
          created_at?: string
          credit_account_id: string
          duplicate_of_lead_id?: string | null
          id?: string
          is_duplicate?: boolean
          lead_id: string
          no_response_warned_at?: string | null
          price_breakdown?: Json
          refund_amount?: number | null
          refund_reason?:
            | Database["public"]["Enums"]["lead_charge_refund_reason"]
            | null
          refund_transaction_id?: string | null
          refunded_at?: string | null
          status?: Database["public"]["Enums"]["lead_charge_status"]
          total_amount?: number
          updated_at?: string
          vendor_id: string
        }
        Update: {
          charge_transaction_id?: string | null
          created_at?: string
          credit_account_id?: string
          duplicate_of_lead_id?: string | null
          id?: string
          is_duplicate?: boolean
          lead_id?: string
          no_response_warned_at?: string | null
          price_breakdown?: Json
          refund_amount?: number | null
          refund_reason?:
            | Database["public"]["Enums"]["lead_charge_refund_reason"]
            | null
          refund_transaction_id?: string | null
          refunded_at?: string | null
          status?: Database["public"]["Enums"]["lead_charge_status"]
          total_amount?: number
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_charges_charge_transaction_id_fkey"
            columns: ["charge_transaction_id"]
            isOneToOne: false
            referencedRelation: "credit_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_charges_credit_account_id_fkey"
            columns: ["credit_account_id"]
            isOneToOne: false
            referencedRelation: "credit_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_charges_duplicate_of_lead_id_fkey"
            columns: ["duplicate_of_lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_charges_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: true
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_charges_refund_transaction_id_fkey"
            columns: ["refund_transaction_id"]
            isOneToOne: false
            referencedRelation: "credit_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_charges_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_message_attachments: {
        Row: {
          created_at: string
          file_id: string
          id: string
          message_id: string
        }
        Insert: {
          created_at?: string
          file_id: string
          id?: string
          message_id: string
        }
        Update: {
          created_at?: string
          file_id?: string
          id?: string
          message_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_message_attachments_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_message_attachments_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "lead_messages"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_messages: {
        Row: {
          content: string
          created_at: string
          id: string
          lead_id: string
          read_at: string | null
          sender_id: string
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          lead_id: string
          read_at?: string | null
          sender_id: string
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          lead_id?: string
          read_at?: string | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_messages_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_reports: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          lead_id: string
          reason: Database["public"]["Enums"]["lead_report_reason"]
          reporter_user_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["lead_report_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          lead_id: string
          reason: Database["public"]["Enums"]["lead_report_reason"]
          reporter_user_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["lead_report_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          lead_id?: string
          reason?: Database["public"]["Enums"]["lead_report_reason"]
          reporter_user_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["lead_report_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_reports_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_status_history: {
        Row: {
          changed_by: string | null
          created_at: string
          from_status: Database["public"]["Enums"]["lead_status"] | null
          id: string
          lead_id: string
          to_status: Database["public"]["Enums"]["lead_status"]
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["lead_status"] | null
          id?: string
          lead_id: string
          to_status: Database["public"]["Enums"]["lead_status"]
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          from_status?: Database["public"]["Enums"]["lead_status"] | null
          id?: string
          lead_id?: string
          to_status?: Database["public"]["Enums"]["lead_status"]
        }
        Relationships: [
          {
            foreignKeyName: "lead_status_history_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_status_history_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          category_ids: string[] | null
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          content: string | null
          created_at: string
          doctor_user_id: string
          id: string
          preferred_channel: string | null
          preferred_time: string | null
          service_name: string | null
          status: Database["public"]["Enums"]["lead_status"]
          updated_at: string
          vendor_id: string
        }
        Insert: {
          category_ids?: string[] | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          content?: string | null
          created_at?: string
          doctor_user_id: string
          id?: string
          preferred_channel?: string | null
          preferred_time?: string | null
          service_name?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          vendor_id: string
        }
        Update: {
          category_ids?: string[] | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          content?: string | null
          created_at?: string
          doctor_user_id?: string
          id?: string
          preferred_channel?: string | null
          preferred_time?: string | null
          service_name?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_doctor_user_id_fkey"
            columns: ["doctor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      membership_plans: {
        Row: {
          created_at: string
          duration_days: number
          id: string
          is_active: boolean
          name: string
          price: number
          promo_expires_at: string | null
          promo_price: number | null
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          duration_days: number
          id?: string
          is_active?: boolean
          name: string
          price: number
          promo_expires_at?: string | null
          promo_price?: number | null
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          duration_days?: number
          id?: string
          is_active?: boolean
          name?: string
          price?: number
          promo_expires_at?: string | null
          promo_price?: number | null
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      notification_deliveries: {
        Row: {
          body_preview: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          error_message: string | null
          failed_at: string | null
          id: string
          max_retries: number
          provider: string
          provider_response: Json | null
          recipient: string
          retry_count: number
          sent_at: string
          status: string
          subject: string | null
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Insert: {
          body_preview?: string | null
          channel: Database["public"]["Enums"]["notification_channel"]
          error_message?: string | null
          failed_at?: string | null
          id?: string
          max_retries?: number
          provider: string
          provider_response?: Json | null
          recipient: string
          retry_count?: number
          sent_at?: string
          status?: string
          subject?: string | null
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Update: {
          body_preview?: string | null
          channel?: Database["public"]["Enums"]["notification_channel"]
          error_message?: string | null
          failed_at?: string | null
          id?: string
          max_retries?: number
          provider?: string
          provider_response?: Json | null
          recipient?: string
          retry_count?: number
          sent_at?: string
          status?: string
          subject?: string | null
          type?: Database["public"]["Enums"]["notification_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_deliveries_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_settings: {
        Row: {
          created_at: string
          email_enabled: boolean
          kakao_enabled: boolean
          lead_enabled: boolean
          marketing_enabled: boolean
          updated_at: string
          user_id: string
          verification_result_enabled: boolean
        }
        Insert: {
          created_at?: string
          email_enabled?: boolean
          kakao_enabled?: boolean
          lead_enabled?: boolean
          marketing_enabled?: boolean
          updated_at?: string
          user_id: string
          verification_result_enabled?: boolean
        }
        Update: {
          created_at?: string
          email_enabled?: boolean
          kakao_enabled?: boolean
          lead_enabled?: boolean
          marketing_enabled?: boolean
          updated_at?: string
          user_id?: string
          verification_result_enabled?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "notification_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_webhooks: {
        Row: {
          created_at: string
          error_message: string | null
          event_type: string
          id: string
          payment_key: string | null
          processed: boolean
          raw_body: Json
          signature: string | null
        }
        Insert: {
          created_at?: string
          error_message?: string | null
          event_type: string
          id?: string
          payment_key?: string | null
          processed?: boolean
          raw_body: Json
          signature?: string | null
        }
        Update: {
          created_at?: string
          error_message?: string | null
          event_type?: string
          id?: string
          payment_key?: string | null
          processed?: boolean
          raw_body?: Json
          signature?: string | null
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          created_at: string
          id: string
          metadata: Json | null
          method: Database["public"]["Enums"]["payment_method"] | null
          order_id: string
          payment_key: string | null
          status: Database["public"]["Enums"]["payment_status"]
          updated_at: string
          user_id: string
          vendor_id: string
        }
        Insert: {
          amount: number
          created_at?: string
          id?: string
          metadata?: Json | null
          method?: Database["public"]["Enums"]["payment_method"] | null
          order_id: string
          payment_key?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          updated_at?: string
          user_id: string
          vendor_id: string
        }
        Update: {
          amount?: number
          created_at?: string
          id?: string
          metadata?: Json | null
          method?: Database["public"]["Enums"]["payment_method"] | null
          order_id?: string
          payment_key?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          updated_at?: string
          user_id?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          email: string | null
          id: string
          marketing_opt_in_at: string | null
          marketing_opt_out_at: string | null
          phone: string | null
          privacy_agreed_at: string | null
          privacy_agreed_version: string | null
          role: Database["public"]["Enums"]["profile_role"]
          status: Database["public"]["Enums"]["profile_status"]
          terms_agreed_at: string | null
          terms_agreed_version: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email?: string | null
          id: string
          marketing_opt_in_at?: string | null
          marketing_opt_out_at?: string | null
          phone?: string | null
          privacy_agreed_at?: string | null
          privacy_agreed_version?: string | null
          role: Database["public"]["Enums"]["profile_role"]
          status?: Database["public"]["Enums"]["profile_status"]
          terms_agreed_at?: string | null
          terms_agreed_version?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          email?: string | null
          id?: string
          marketing_opt_in_at?: string | null
          marketing_opt_out_at?: string | null
          phone?: string | null
          privacy_agreed_at?: string | null
          privacy_agreed_version?: string | null
          role?: Database["public"]["Enums"]["profile_role"]
          status?: Database["public"]["Enums"]["profile_status"]
          terms_agreed_at?: string | null
          terms_agreed_version?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      rate_limits: {
        Row: {
          action: string
          created_at: string
          id: string
          request_count: number
          target_id: string | null
          updated_at: string
          user_id: string
          window_start: string
        }
        Insert: {
          action: string
          created_at?: string
          id?: string
          request_count?: number
          target_id?: string | null
          updated_at?: string
          user_id: string
          window_start: string
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          request_count?: number
          target_id?: string | null
          updated_at?: string
          user_id?: string
          window_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "rate_limits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      recent_views: {
        Row: {
          last_viewed_at: string
          user_id: string
          vendor_id: string
          view_count: number
        }
        Insert: {
          last_viewed_at?: string
          user_id: string
          vendor_id: string
          view_count?: number
        }
        Update: {
          last_viewed_at?: string
          user_id?: string
          vendor_id?: string
          view_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "recent_views_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recent_views_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          reason: Database["public"]["Enums"]["report_reason"]
          reporter_user_id: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["report_status"]
          target_id: string
          target_type: Database["public"]["Enums"]["report_target_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          reason: Database["public"]["Enums"]["report_reason"]
          reporter_user_id: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          target_id: string
          target_type: Database["public"]["Enums"]["report_target_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          reason?: Database["public"]["Enums"]["report_reason"]
          reporter_user_id?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          target_id?: string
          target_type?: Database["public"]["Enums"]["report_target_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_reporter_user_id_fkey"
            columns: ["reporter_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      review_reports: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          reason: Database["public"]["Enums"]["review_report_reason"]
          reporter_user_id: string
          review_id: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["review_report_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          reason: Database["public"]["Enums"]["review_report_reason"]
          reporter_user_id: string
          review_id: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["review_report_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          reason?: Database["public"]["Enums"]["review_report_reason"]
          reporter_user_id?: string
          review_id?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["review_report_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_reports_reporter_user_id_fkey"
            columns: ["reporter_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_reports_review_id_fkey"
            columns: ["review_id"]
            isOneToOne: false
            referencedRelation: "reviews"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_reports_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          amount: number | null
          content: string
          created_at: string
          doctor_user_id: string
          id: string
          lead_id: string | null
          photo_file_ids: string[]
          rating: number
          status: Database["public"]["Enums"]["review_status"]
          updated_at: string
          vendor_id: string
          worked_at: string | null
        }
        Insert: {
          amount?: number | null
          content: string
          created_at?: string
          doctor_user_id: string
          id?: string
          lead_id?: string | null
          photo_file_ids?: string[]
          rating: number
          status?: Database["public"]["Enums"]["review_status"]
          updated_at?: string
          vendor_id: string
          worked_at?: string | null
        }
        Update: {
          amount?: number | null
          content?: string
          created_at?: string
          doctor_user_id?: string
          id?: string
          lead_id?: string | null
          photo_file_ids?: string[]
          rating?: number
          status?: Database["public"]["Enums"]["review_status"]
          updated_at?: string
          vendor_id?: string
          worked_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_doctor_user_id_fkey"
            columns: ["doctor_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      sanctions: {
        Row: {
          created_at: string
          created_by: string | null
          duration_days: number | null
          ends_at: string | null
          id: string
          reason: string
          report_id: string | null
          revoke_reason: string | null
          revoked_at: string | null
          revoked_by: string | null
          sanction_type: Database["public"]["Enums"]["sanction_type"]
          starts_at: string
          status: Database["public"]["Enums"]["sanction_status"]
          target_id: string
          target_type: Database["public"]["Enums"]["report_target_type"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          duration_days?: number | null
          ends_at?: string | null
          id?: string
          reason: string
          report_id?: string | null
          revoke_reason?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          sanction_type: Database["public"]["Enums"]["sanction_type"]
          starts_at?: string
          status?: Database["public"]["Enums"]["sanction_status"]
          target_id: string
          target_type: Database["public"]["Enums"]["report_target_type"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          duration_days?: number | null
          ends_at?: string | null
          id?: string
          reason?: string
          report_id?: string | null
          revoke_reason?: string | null
          revoked_at?: string | null
          revoked_by?: string | null
          sanction_type?: Database["public"]["Enums"]["sanction_type"]
          starts_at?: string
          status?: Database["public"]["Enums"]["sanction_status"]
          target_id?: string
          target_type?: Database["public"]["Enums"]["report_target_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sanctions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sanctions_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sanctions_revoked_by_fkey"
            columns: ["revoked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription_plans: {
        Row: {
          created_at: string
          daily_rate: number
          discount_rate: number
          duration_days: number
          id: string
          is_active: boolean
          name: string
          price: number
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          daily_rate: number
          discount_rate?: number
          duration_days: number
          id?: string
          is_active?: boolean
          name: string
          price: number
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          daily_rate?: number
          discount_rate?: number
          duration_days?: number
          id?: string
          is_active?: boolean
          name?: string
          price?: number
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      user_onboarding_steps: {
        Row: {
          completed_at: string | null
          created_at: string
          skipped_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          skipped_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          skipped_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_onboarding_steps_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_categories: {
        Row: {
          category_id: string
          created_at: string
          vendor_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          vendor_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_categories_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_categories_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_membership_reminder_logs: {
        Row: {
          created_at: string
          id: string
          membership_id: string
          reminder_days_before: number
          sent_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          membership_id: string
          reminder_days_before: number
          sent_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          membership_id?: string
          reminder_days_before?: number
          sent_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_membership_reminder_logs_membership_id_fkey"
            columns: ["membership_id"]
            isOneToOne: false
            referencedRelation: "vendor_memberships"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_memberships: {
        Row: {
          auto_renew: boolean
          canceled_at: string | null
          created_at: string
          credit_transaction_id: string | null
          expires_at: string
          id: string
          payment_id: string | null
          plan_id: string
          price_paid: number
          starts_at: string
          status: string
          updated_at: string
          vendor_id: string
        }
        Insert: {
          auto_renew?: boolean
          canceled_at?: string | null
          created_at?: string
          credit_transaction_id?: string | null
          expires_at: string
          id?: string
          payment_id?: string | null
          plan_id: string
          price_paid: number
          starts_at?: string
          status?: string
          updated_at?: string
          vendor_id: string
        }
        Update: {
          auto_renew?: boolean
          canceled_at?: string | null
          created_at?: string
          credit_transaction_id?: string | null
          expires_at?: string
          id?: string
          payment_id?: string | null
          plan_id?: string
          price_paid?: number
          starts_at?: string
          status?: string
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_memberships_credit_transaction_id_fkey"
            columns: ["credit_transaction_id"]
            isOneToOne: false
            referencedRelation: "credit_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_memberships_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: false
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_memberships_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "membership_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_memberships_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_portfolio_assets: {
        Row: {
          created_at: string
          file_id: string | null
          id: string
          portfolio_id: string
          sort_order: number
          url: string | null
        }
        Insert: {
          created_at?: string
          file_id?: string | null
          id?: string
          portfolio_id: string
          sort_order?: number
          url?: string | null
        }
        Update: {
          created_at?: string
          file_id?: string | null
          id?: string
          portfolio_id?: string
          sort_order?: number
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "vendor_portfolio_assets_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_portfolio_assets_portfolio_id_fkey"
            columns: ["portfolio_id"]
            isOneToOne: false
            referencedRelation: "vendor_portfolios"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_portfolios: {
        Row: {
          created_at: string
          description: string | null
          id: string
          sort_order: number
          title: string | null
          updated_at: string
          vendor_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          sort_order?: number
          title?: string | null
          updated_at?: string
          vendor_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          sort_order?: number
          title?: string | null
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_portfolios_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_service_prices: {
        Row: {
          category_id: string
          created_at: string
          daily_budget_limit: number | null
          id: string
          price: number
          status: Database["public"]["Enums"]["vendor_service_price_status"]
          updated_at: string
          vendor_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          daily_budget_limit?: number | null
          id?: string
          price: number
          status?: Database["public"]["Enums"]["vendor_service_price_status"]
          updated_at?: string
          vendor_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          daily_budget_limit?: number | null
          id?: string
          price?: number
          status?: Database["public"]["Enums"]["vendor_service_price_status"]
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_service_prices_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_service_prices_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_subscription_reminder_logs: {
        Row: {
          created_at: string
          id: string
          reminder_days_before: number
          sent_at: string
          subscription_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reminder_days_before: number
          sent_at?: string
          subscription_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reminder_days_before?: number
          sent_at?: string
          subscription_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_subscription_reminder_logs_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "vendor_subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_subscriptions: {
        Row: {
          auto_renew: boolean
          canceled_at: string | null
          category_id: string
          created_at: string
          credit_transaction_id: string | null
          expires_at: string
          id: string
          lead_count: number
          plan_id: string
          price_paid: number
          starts_at: string
          status: Database["public"]["Enums"]["subscription_status"]
          updated_at: string
          vendor_id: string
        }
        Insert: {
          auto_renew?: boolean
          canceled_at?: string | null
          category_id: string
          created_at?: string
          credit_transaction_id?: string | null
          expires_at: string
          id?: string
          lead_count?: number
          plan_id: string
          price_paid: number
          starts_at?: string
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
          vendor_id: string
        }
        Update: {
          auto_renew?: boolean
          canceled_at?: string | null
          category_id?: string
          created_at?: string
          credit_transaction_id?: string | null
          expires_at?: string
          id?: string
          lead_count?: number
          plan_id?: string
          price_paid?: number
          starts_at?: string
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_subscriptions_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_subscriptions_credit_transaction_id_fkey"
            columns: ["credit_transaction_id"]
            isOneToOne: false
            referencedRelation: "credit_transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "subscription_plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_subscriptions_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "vendors"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_verifications: {
        Row: {
          business_license_file_id: string | null
          business_no: string
          company_name: string
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string
          id: string
          reject_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["verification_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          business_license_file_id?: string | null
          business_no: string
          company_name: string
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          business_license_file_id?: string | null
          business_no?: string
          company_name?: string
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          id?: string
          reject_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_verifications_business_license_file_id_fkey"
            columns: ["business_license_file_id"]
            isOneToOne: false
            referencedRelation: "files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_verifications_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_verifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      vendors: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          owner_user_id: string
          price_max: number | null
          price_min: number | null
          rating_avg: number | null
          region_primary: string | null
          region_secondary: string | null
          review_count: number
          status: Database["public"]["Enums"]["vendor_status"]
          summary: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_user_id: string
          price_max?: number | null
          price_min?: number | null
          rating_avg?: number | null
          region_primary?: string | null
          region_secondary?: string | null
          review_count?: number
          status?: Database["public"]["Enums"]["vendor_status"]
          summary?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_user_id?: string
          price_max?: number | null
          price_min?: number | null
          rating_avg?: number | null
          region_primary?: string | null
          region_secondary?: string | null
          review_count?: number
          status?: Database["public"]["Enums"]["vendor_status"]
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendors_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_create_lead: { Args: { target_vendor_id: string }; Returns: boolean }
      can_write_review: {
        Args: { target_lead_id: string; target_vendor_id: string }
        Returns: boolean
      }
      charge_bid_commission: {
        Args: { p_contract_id: string; p_vendor_id: string }
        Returns: {
          new_balance: number
          transaction_id: string
        }[]
      }
      credit_balance_update: {
        Args: {
          p_amount: number
          p_credit_account_id: string
          p_description?: string
          p_expires_at?: string
          p_transaction_id: string
          p_type: Database["public"]["Enums"]["credit_transaction_type"]
        }
        Returns: {
          new_balance: number
          transaction_id: string
        }[]
      }
      current_profile_role: {
        Args: never
        Returns: Database["public"]["Enums"]["profile_role"]
      }
      has_active_vendor_membership: {
        Args: { p_reference_time?: string; p_vendor_id: string }
        Returns: boolean
      }
      has_active_vendor_subscription: {
        Args: {
          p_category_id: string
          p_reference_time?: string
          p_vendor_id: string
        }
        Returns: boolean
      }
      is_admin: { Args: never; Returns: boolean }
      is_approved_doctor: { Args: never; Returns: boolean }
      is_vendor_approved: { Args: { vendor_id: string }; Returns: boolean }
      is_vendor_owner: { Args: { vendor_id: string }; Returns: boolean }
      is_vendor_public: { Args: { vendor_id: string }; Returns: boolean }
      purchase_ad_priority_slot: {
        Args: { p_priority_slot_id: string; p_vendor_id: string }
        Returns: {
          purchase_id: string
          transaction_id: string
        }[]
      }
      purchase_vendor_membership: {
        Args: { p_auto_renew?: boolean; p_plan_id: string; p_vendor_id: string }
        Returns: {
          membership_id: string
          new_balance: number
          transaction_id: string
          was_extended: boolean
        }[]
      }
      purchase_vendor_subscription: {
        Args: {
          p_auto_renew?: boolean
          p_category_id: string
          p_extension_window_days?: number
          p_plan_id: string
          p_vendor_id: string
        }
        Returns: {
          new_balance: number
          subscription_id: string
          transaction_id: string
          was_extended: boolean
        }[]
      }
      refresh_vendor_rating: {
        Args: { target_vendor_id: string }
        Returns: undefined
      }
      resolve_report: {
        Args: {
          p_admin_user_id: string
          p_duration_days?: number
          p_reason: string
          p_report_id: string
          p_sanction_type?: Database["public"]["Enums"]["sanction_type"]
        }
        Returns: Json
      }
    }
    Enums: {
      ad_campaign_status:
        | "draft"
        | "pending"
        | "active"
        | "paused"
        | "completed"
        | "canceled"
      ad_creative_type: "image" | "html"
      ad_priority_purchase_status:
        | "active"
        | "expired"
        | "canceled"
        | "refunded"
      ad_priority_tier: "premium" | "plus_up" | "plus" | "rookie"
      ad_slot_position: "main" | "sub"
      bid_commission_status: "pending" | "charged" | "refunded" | "waived"
      bid_contract_status:
        | "pending"
        | "active"
        | "completed"
        | "canceled"
        | "disputed"
      bid_project_status:
        | "draft"
        | "open"
        | "bidding"
        | "selecting"
        | "contracted"
        | "in_progress"
        | "completed"
        | "settled"
        | "canceled"
      bid_response_status:
        | "invited"
        | "submitted"
        | "selected"
        | "rejected"
        | "withdrawn"
        | "expired"
      credit_transaction_status: "pending" | "completed" | "failed" | "canceled"
      credit_transaction_type:
        | "charge"
        | "charge_bonus"
        | "deduct"
        | "refund"
        | "recovery"
        | "expire"
        | "admin_adjust"
      file_purpose:
        | "doctor_license"
        | "vendor_business_license"
        | "portfolio"
        | "lead_attachment"
        | "avatar"
        | "review_photo"
        | "lead_message_attachment"
      help_article_type: "faq" | "notice" | "guide"
      lead_charge_refund_reason:
        | "duplicate_30d"
        | "no_response_72h"
        | "fraud_auto_filter"
        | "fraud_vendor_report"
        | "admin_manual"
      lead_charge_status:
        | "charged"
        | "pending"
        | "refunded"
        | "waived"
        | "failed"
      lead_report_reason:
        | "wrong_contact"
        | "test_inquiry"
        | "competitor"
        | "inappropriate"
        | "other"
      lead_report_status: "pending" | "approved" | "dismissed"
      lead_status:
        | "submitted"
        | "in_progress"
        | "quote_pending"
        | "negotiating"
        | "contracted"
        | "hold"
        | "canceled"
        | "closed"
      notification_channel: "email" | "kakao" | "sms" | "in_app"
      notification_type:
        | "verification_approved"
        | "verification_rejected"
        | "lead_received"
        | "lead_responded"
        | "review_received"
        | "lead_message_received"
        | "membership_expiring"
        | "subscription_expiring"
        | "lead_charged"
        | "lead_refunded"
        | "credit_low"
        | "lead_no_response_warning"
        | "bid_vendor_invited"
        | "bid_response_submitted"
        | "bid_vendor_selected"
        | "bid_commission_charged"
      payment_method:
        | "card"
        | "virtual_account"
        | "transfer"
        | "mobile"
        | "easy_pay"
        | "etc"
      payment_status:
        | "ready"
        | "in_progress"
        | "done"
        | "canceled"
        | "partial_canceled"
        | "aborted"
        | "expired"
      profile_role: "doctor" | "vendor" | "admin"
      profile_status: "active" | "inactive" | "banned"
      report_reason:
        | "spam"
        | "inappropriate"
        | "false_info"
        | "privacy"
        | "other"
      report_status: "pending" | "reviewing" | "resolved" | "dismissed"
      report_target_type: "review" | "vendor" | "profile"
      review_report_reason:
        | "spam"
        | "inappropriate"
        | "false_info"
        | "privacy"
        | "other"
      review_report_status: "pending" | "reviewed" | "dismissed"
      review_status: "published" | "hidden"
      sanction_status: "active" | "expired" | "revoked"
      sanction_type: "warning" | "suspension" | "permanent_ban"
      subscription_status: "active" | "expired" | "canceled"
      vendor_service_price_status: "active" | "archived"
      vendor_status: "draft" | "active" | "inactive" | "banned"
      verification_status: "pending" | "approved" | "rejected"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      ad_campaign_status: [
        "draft",
        "pending",
        "active",
        "paused",
        "completed",
        "canceled",
      ],
      ad_creative_type: ["image", "html"],
      ad_priority_purchase_status: [
        "active",
        "expired",
        "canceled",
        "refunded",
      ],
      ad_priority_tier: ["premium", "plus_up", "plus", "rookie"],
      ad_slot_position: ["main", "sub"],
      bid_commission_status: ["pending", "charged", "refunded", "waived"],
      bid_contract_status: [
        "pending",
        "active",
        "completed",
        "canceled",
        "disputed",
      ],
      bid_project_status: [
        "draft",
        "open",
        "bidding",
        "selecting",
        "contracted",
        "in_progress",
        "completed",
        "settled",
        "canceled",
      ],
      bid_response_status: [
        "invited",
        "submitted",
        "selected",
        "rejected",
        "withdrawn",
        "expired",
      ],
      credit_transaction_status: ["pending", "completed", "failed", "canceled"],
      credit_transaction_type: [
        "charge",
        "charge_bonus",
        "deduct",
        "refund",
        "recovery",
        "expire",
        "admin_adjust",
      ],
      file_purpose: [
        "doctor_license",
        "vendor_business_license",
        "portfolio",
        "lead_attachment",
        "avatar",
        "review_photo",
        "lead_message_attachment",
      ],
      help_article_type: ["faq", "notice", "guide"],
      lead_charge_refund_reason: [
        "duplicate_30d",
        "no_response_72h",
        "fraud_auto_filter",
        "fraud_vendor_report",
        "admin_manual",
      ],
      lead_charge_status: [
        "charged",
        "pending",
        "refunded",
        "waived",
        "failed",
      ],
      lead_report_reason: [
        "wrong_contact",
        "test_inquiry",
        "competitor",
        "inappropriate",
        "other",
      ],
      lead_report_status: ["pending", "approved", "dismissed"],
      lead_status: [
        "submitted",
        "in_progress",
        "quote_pending",
        "negotiating",
        "contracted",
        "hold",
        "canceled",
        "closed",
      ],
      notification_channel: ["email", "kakao", "sms", "in_app"],
      notification_type: [
        "verification_approved",
        "verification_rejected",
        "lead_received",
        "lead_responded",
        "review_received",
        "lead_message_received",
        "membership_expiring",
        "subscription_expiring",
        "lead_charged",
        "lead_refunded",
        "credit_low",
        "lead_no_response_warning",
        "bid_vendor_invited",
        "bid_response_submitted",
        "bid_vendor_selected",
        "bid_commission_charged",
      ],
      payment_method: [
        "card",
        "virtual_account",
        "transfer",
        "mobile",
        "easy_pay",
        "etc",
      ],
      payment_status: [
        "ready",
        "in_progress",
        "done",
        "canceled",
        "partial_canceled",
        "aborted",
        "expired",
      ],
      profile_role: ["doctor", "vendor", "admin"],
      profile_status: ["active", "inactive", "banned"],
      report_reason: [
        "spam",
        "inappropriate",
        "false_info",
        "privacy",
        "other",
      ],
      report_status: ["pending", "reviewing", "resolved", "dismissed"],
      report_target_type: ["review", "vendor", "profile"],
      review_report_reason: [
        "spam",
        "inappropriate",
        "false_info",
        "privacy",
        "other",
      ],
      review_report_status: ["pending", "reviewed", "dismissed"],
      review_status: ["published", "hidden"],
      sanction_status: ["active", "expired", "revoked"],
      sanction_type: ["warning", "suspension", "permanent_ban"],
      subscription_status: ["active", "expired", "canceled"],
      vendor_service_price_status: ["active", "archived"],
      vendor_status: ["draft", "active", "inactive", "banned"],
      verification_status: ["pending", "approved", "rejected"],
    },
  },
} as const
