import fs from "node:fs/promises";
import path from "node:path";

import { appRoot, runSupabaseCaptureStdout } from "./_supabase";

async function main() {
	const args = process.argv.slice(2).filter((arg) => arg !== "--");
	const outputPath = path.resolve(appRoot, "src/lib/database.types.ts");

	function hasFlag(flag: string): boolean {
		return args.includes(flag);
	}

	function hasFlagWithValue(flag: string): boolean {
		return args.some((arg) => arg === flag) || args.some((arg) => arg.startsWith(`${flag}=`));
	}

	const schema = process.env.SUPABASE_SCHEMA ?? "public";
	const shouldIncludeSchemaFlag = !hasFlagWithValue("--schema");

	const projectIdFromEnv = process.env.SUPABASE_PROJECT_ID;
	const hasProjectIdFlag = hasFlagWithValue("--project-id");
	const isLocal = hasFlag("--local");

	if (!isLocal && !hasProjectIdFlag && !projectIdFromEnv) {
		console.error(
			[
				"Missing SUPABASE_PROJECT_ID.",
				"",
				"Options:",
				'  - Set SUPABASE_PROJECT_ID in your env and run: pnpm db:gen',
				'  - Pass project id directly: pnpm db:gen -- --project-id <project_ref>',
				"  - Generate from local DB (requires `supabase start`): pnpm db:gen -- --local",
			].join("\n"),
		);
		process.exit(1);
	}

	const supabaseArgs = ["gen", "types", "typescript"];

	if (!isLocal && !hasProjectIdFlag && projectIdFromEnv) {
		supabaseArgs.push("--project-id", projectIdFromEnv);
	}

	if (shouldIncludeSchemaFlag) {
		supabaseArgs.push("--schema", schema);
	}

	supabaseArgs.push(...args);

	const types = await runSupabaseCaptureStdout(supabaseArgs);

	await fs.mkdir(path.dirname(outputPath), { recursive: true });
	await fs.writeFile(
		outputPath,
		[
			"/* eslint-disable */",
			"/* This file is auto-generated by `pnpm db:gen`. Do not edit manually. */",
			"",
			types.trimEnd(),
			"",
		].join("\n"),
		"utf8",
	);

	console.info(`✅ Generated: ${path.relative(appRoot, outputPath)}`);
}

main().catch((error) => {
	console.error("❌ db:gen failed:", error);
	process.exit(1);
});
